# Generated by Django 2.2.12 on 2020-04-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
