# Generated by Django 2.2.12 on 2020-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='guild',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
