# Generated by Django 2.2.12 on 2020-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='guild',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
