# Generated by Django 2.2.12 on 2020-04-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_date_created'),
        ('main_app', '0006_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='guild',
            field=models.CharField(max_length=100),
        ),
    ]
