# Generated by Django 2.2.12 on 2020-04-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200419_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AlterField(
            model_name='comments',
            name='guild',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
