# Generated by Django 2.2.12 on 2020-04-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20200419_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='guild',
            field=models.CharField(default='#your_guild_name::your_nickname', max_length=100),
        ),
    ]
